---
title: "City of San Diego streetlights with missing and/or incorrect associated information (~16% of > 60k lights)"
author: "- Nick Haring"

output: 
    flexdashboard::flex_dashboard:
    theme: journal
source_code: embed
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(flexdashboard)
library(shiny)
library(jsonlite)
library(maptools)
library(ggplot2)
library(tidyr)
library(dplyr)
library(purrr)
library(leaflet)
library(plotly)

sl_issues <- read.csv("shiny_streetlight_issues.csv", stringsAsFactors = FALSE) %>% 
    mutate(., ratingcol = case_when(N > 1 ~ "red", # creating some conditional labels for the map
                                    streetlight_voltage < 120 ~ "black",
                                    !is.na(lat) ~ "deepskyblue"))
```


Column {data-width = 650}
-----------------------------------------------------------------------

### Streetlight data from streetlight_locations_datasd_v1, see: https://data.sandiego.gov/datasets/streetlight_inventory/

```{r echo=FALSE}
leaflet() %>% 
  addTiles() %>% 
  fitBounds(-117.663817,33.077762,-116.584410,32.559574) %>% 
  addCircleMarkers(sl_issues$lng, 
                   sl_issues$lat, 
                   color = sl_issues$ratingcol, 
                   radius = 1.5, 
                   fill = T,
                   fillOpacity = 0.2,
                   opacity = 0.6,
                   popup = paste("Streetlight type = ", sl_issues$streetlight_type, sep = "")) %>%
  addLegend("bottomleft",
            colors = c("red", "black", "deepskyblue"),
            labels = c( "Multiple data row and missing SAP ID and location description",
                        "Incorrect voltage and missing SAP ID and location description",
                        "Missing SAP ID and location description"),
            opacity = 0.8)

                                 

            
```

Column {data-width=350}
-----------------------------------------------------------------------
### Streetlight Types

```{r echo=FALSE}
bar_chart <- sl_issues %>% 
  select(., streetlight_type)

bar_chart$streetlight_type <- forcats::fct_explicit_na(sl_issues$streetlight_type)

bar_chart %>% 
  count(., streetlight_type) %>%
  plot_ly(data = ., 
          type = "bar", 
          x = as.character(.$streetlight_type), 
          y = .$n, 
          color = as.character(.$streetlight_type)) %>%
  layout(xaxis = list(showline = F, 
                      showticklabels = F, 
                      fixedrange = T, 
                      title = ""),
         yaxis = list(fixedrange = T, 
                      title = ""))
```

### Streetlights potentially outside of City borders

```{r echo=FALSE}
leaflet() %>% 
  addTiles() %>% 
  fitBounds(-117.663817,33.133762,-116.584410,32.559574) %>% 
  addCircleMarkers(sl_issues[sl_issues$lat > 33.15740 | sl_issues$lng > -116.9278, ]$lng,
                   sl_issues[sl_issues$lat > 33.15740 | sl_issues$lng > -116.9278, ]$lat,
                   color = "orange", 
                   radius = 2, 
                   fill = T,
                   fillOpacity = 0.2,
                   opacity = 0.6,
                   popup = paste(sl_issues[sl_issues$lat > 33.15740, ]$lat,
                                 sl_issues[sl_issues$lat > 33.15740, ]$lng, 
                                 sep = " "))


```



